name: e2e

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  e2e-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    env:
      VITE_BASE_URL: 'http://localhost:1337'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Start Application and Run Cypress on ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          start: npx serve -s dist -l 5173
          wait-on: 'http://localhost:5173'

  e2e-safari:
    runs-on: macos-latest
    env:
      VITE_BASE_URL: 'http://localhost:1337'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Start Application and Run Cypress on Safari
        uses: cypress-io/github-action@v6
        with:
          browser: safari
          start: npx serve -s dist -l 5173
          wait-on: 'http://localhost:5173'
